[package]
name = "dhcp-framed"
version = "0.1.0"
authors = ["hedgar <hedgar2017@gmail.com>"]

[dependencies]
tokio = "0.1.7"
futures = "0.1.21"
net2 = "0.2.33"
dhcp-protocol = { path = "../protocol" }